# linear algebra using python user defined function without using  Numpy linalg

# Addition

In [1]:

def matrix_addition(matrix1, matrix2):
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        raise ValueError("Matrix dimensions must match for addition")
    
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)
    
    return result

matrix1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix2 = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

result_matrix = matrix_addition(matrix1, matrix2)

for row in result_matrix:
    print(row)


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


# substraction

In [2]:
def subtract_matrices(matrix1, matrix2):
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        raise ValueError("Matrices must have the same dimensions for subtraction")

    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] - matrix2[i][j])
        result.append(row)

    return result

matrix1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]


matrix2 = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]]


result = subtract_matrices(matrix1, matrix2)

for row in result:
    print(row)


[-8, -6, -4]
[-2, 0, 2]
[4, 6, 8]


# matrix dot product

In [3]:

A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

C = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]

for row in C:
    print(row)


[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


# Matrix determinant and Trnspose

In [7]:
class Matrix:
    def __init__(self, data):
        self.data = data
        self.rows = len(data)
        self.cols = len(data[0])

    def __str__(self):
        return '\n'.join([' '.join(map(str, row)) for row in self.data])

    def __getitem__(self, indices):
        i, j = indices
        return self.data[i][j]

    def __setitem__(self, indices, value):
        i, j = indices
        self.data[i][j] = value




    def determinant(self):
        if self.rows != self.cols:
            raise ValueError("Determinant is only defined for square matrices.")
        if self.rows == 1:
            return self[0, 0]
        elif self.rows == 2:
            return self[0, 0] * self[1, 1] - self[0, 1] * self[1, 0]
        else:
            det = 0
            for j in range(self.cols):
                det += (-1) ** j * self[0, j] * self.minor(0, j).determinant()
            return det
    def minor(self, row, col):
        minor_data = [
            [self.data[i][j] for j in range(self.cols) if j != col]
            for i in range(self.rows) if i != row
        ]
        return Matrix(minor_data)
    

    def transpose(self):
        transposed_data = [
            [self.data[j][i] for j in range(self.rows)]
            for i in range(self.cols)
        ]
        return Matrix(transposed_data)

In [8]:
matrix1 = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = Matrix([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

Matrix 1:
1 2 3
4 5 6
7 8 9

Matrix 2:
9 8 7
6 5 4
3 2 1


In [9]:
# Determinant
det = matrix1.determinant()
print("\nDeterminant of Matrix 1:", det)
det1 = matrix2.determinant()
print("\nDeterminant of Matrix 2:", det1)
# Transpose
transposed_matrix = matrix1.transpose()
print("\nTranspose of Matrix 1:")
print(transposed_matrix)

transposed_matrix1 = matrix2.transpose()
print("\nTranspose of Matrix 2:")
print(transposed_matrix1)


Determinant of Matrix 1: 0

Determinant of Matrix 2: 0

Transpose of Matrix 1:
1 4 7
2 5 8
3 6 9

Transpose of Matrix 2:
9 6 3
8 5 2
7 4 1


# using Numpy linalg function

In [11]:
import numpy as np
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])  

det = np.linalg.det(matrix1)
  
print("Determinant of matrix1 is : ")
print(int(det))
det1 = np.linalg.det(matrix2)
  
print("Determinant of matrix2 is : ")
print(int(det1))

Determinant of matrix1 is : 
0
Determinant of matrix2 is : 
0


In [12]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [13]:
matrix1.dot(matrix2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [14]:
np.transpose(matrix1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
np.transpose(matrix2)

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])